[package]
name = "mist"
version = "0.0.1-alpha2"
edition = "2024"
description = "The Mist programming language compiler"
license = "MIT"
repository = "https://github.com/mist-go/mist"
readme = "README.md"
keywords = ["compiler", "language", "mist"]
categories = ["compilers"]

[dependencies]
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
parser = { path = "./parser" }

[[bin]]
name = "mist"
path = "src/main.rs"
