[package]
name = "mist-lang"
version = "0.0.4-alpha0"
edition = "2024"
description = "The Mist programming language compiler"
license = "Apache-2.0"
repository = "https://github.com/mist-go/mist"
readme = "README.md"
keywords = ["compiler", "language", "mist"]
categories = ["compilers"]
default-run = "mist"
include = [
    ".mist/src/**",
    "Cargo.toml",
    "README.md",
]

[dependencies]
mist-parser = { workspace = true }
mist-analyzer = { workspace = true }
mist-codegen = { workspace = true }

serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
cargo_metadata = "0.23.1"

[workspace.dependencies]
mist-parser = { path = "./parser", version = "0.1.5" }
mist-analyzer = { path = "./analyzer", version = "0.0.2" }
mist-codegen = { path = "./codegen", version = "0.1.1" }

[[bin]]
name = "mist"
path = ".mist/src/main.rs"

[[bin]]
name = "mist-header"
path = "src/_header.rs"

[[bin]]
name = "mist-analyzer"
path = ".mist/src/analyzer.rs"
