[package]
name = "mist-analyzer"
version = "0.0.1"
edition = "2024"
description = "The Mist programming language Analzyer LSP"
license = "Apache-2.0"
repository = "https://github.com/mist-go/mist"
keywords = ["language-server", "language", "mist"]
categories = ["language-servers"]

[dependencies]
tokio = { version = "1.52.3", features = ["full", "macros", "rt", "rt-multi-thread"] }
tower-lsp = "0.20.0"
