[package]
name = "mist-parser"
version = "0.1.5"
edition = "2024"
description = "The Mist programming language parser"
license = "Apache-2.0"
repository = "https://github.com/mist-go/mist"
keywords = ["compiler", "language", "mist"]
categories = ["compilers", "parser-implementations", "parsing"]

[dependencies]
pest = "2.8.6"
pest_derive = "2.8.6"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
