[package]
name = "mist-codegen"
version = "0.3.5-alpha.0"
edition = "2024"
description = "The Mist programming language Rust code generator"
license = "Apache-2.0"
repository = "https://github.com/mist-go/mist"
keywords = ["compiler", "language", "mist"]
categories = ["compilers"]

[dependencies]
bytecount = "0.6.9"
mist-parser = { workspace = true }
